FROM oven/bun:1

WORKDIR /usr/src/app

RUN apt-get update \
  && apt-get install -y --no-install-recommends openssl \
  && rm -rf /var/lib/apt/lists/*

COPY ./packages ./packages
COPY ./bun.lock ./bun.lock

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./apps/http-backend ./apps/http-backend

RUN bun install
RUN bun run db:generate

EXPOSE 8080

CMD ["bun", "run", "start:http-backend"]