name: deploy backend
on:
    push:
        branches: ["main"]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout the code
              uses: actions/checkout@v2

            - name: login to dockerhub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            
            - name: build and push to dockerhub
              uses: docker/build-push-action@v4
              with:
                context: .
                file: ./docker/Dockerfile.backend
                push: true
                tags: rshdhere/monorepo-backend:${{ github.sha }}
            
            - name: deploy to the VM
              run: |
                 echo "${{ secrets.SSH_PRIVATE_KEY }}" &> ~/ssh_key
                 chmod 700 /home/runner/ssh_key
                 ssh -o StrictHostKeyChecking=no -i ~/ssh_key root@128.199.20.241 -t "docker stop user_backend && docker run --name user_backend -d -p 8080:8080 rshdhere/monorepo-backend:${{ github.sha }}"
